# Generated by Django 3.1.3 on 2020-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='favorite_book',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
