# Generated by Django 3.1.3 on 2020-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201122_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_picture',
            field=models.URLField(default='https://www.pngitem.com/pimgs/m/146-1468843_profile-icon-orange-png-transparent-png.png'),
        ),
    ]
