# Generated by Django 3.1.3 on 2020-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='image_url',
        ),
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes'),
        ),
    ]
